from enum import Enum


class SecTypes(Enum):
    AssetBacket = "Asset Backet"
    BankDebt = "Bank Debt"
    Bond = "Bond"
    BondConvertible = "Bond Convertible"
    BondCorporate = "Bond Corporate"
    BondGovernment = "Bond Government"
    BondSovereign = "Bond Sovereign"
    Commodity = "Commodity"
    CommoditySwap = "Commodity Swap"
    CreditContract = "Credit Contract"
    CreditDerivatives = "Credit Derivatives"
    CreditIndex = "Credit Index"
    CumulativePreferred = "Cumulative Preferred"
    Currency = "Currency"
    Depository = "Depository"
    DepositoryReceipt = "Depository Receipt"
    EquityPreferred = "Equity Preferred"
    Equity = "Equity"
    EquityRight = "Equity Right"
    EquityUnit = "Equity Unit"
    ExchangeTradedFund = "Exchange Traded Fund"
    Fund = "Fund"
    Future = "Future"
    Hybrid = "Hybrid"
    Index = "Index"
    IndexAndNonEquityOption = "Index and Non-equity Option"
    ListedOption = "Listed Option"
    OTCOption = "OTC Option"
    PreferredConvertible = "Preferred Convertible"
    Rate = "Rate"
    RepoLoan = "Repo Loan"
    VarianceSwap = "Variance Swap"
    Warrant = "Warrant"

class SecTypeErrors(Enum):
    WRONG_SECTYPE = "Please, check that you use correct Sec_type"
